# Generated by Django 3.1.4 on 2020-12-04 10:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('url_name', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('geofencing_message', models.TextField(blank=True)),
                ('map_center', models.JSONField(null=True)),
                ('map_zoom_level', models.IntegerField(null=True)),
                ('basemap', models.JSONField(null=True)),
                ('geofencing_layer_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeofencePoly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('map_url_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geofx_app.map')),
            ],
        ),
    ]
