# Generated by Django 3.1.4 on 2020-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofx_app', '0002_auto_20201215_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='geofencing_message',
            new_name='fence_enter_message',
        ),
        migrations.AddField(
            model_name='map',
            name='fence_leave_message',
            field=models.TextField(blank=True),
        ),
    ]
